version: 2.1

orbs:
  python: circleci/python@0.2.1
  # An orb for Google Kubernetes Engine (GKE)
  gcp-gke: circleci/gcp-gke@1.0.3
  # An orb for Google Container Registry (GCR) 
  gcp-gcr: circleci/gcp-gcr@0.6.1

jobs:
  build_and_test:
    # run the steps with Docker
    docker:
      - image: circleci/python:3.9.0a4-buster
    description: Update dependencies and run tests
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python3 -m pytest
          name: Test

  build_push_image:
    description: Build and push the image to GCR
    machine: true
    steps:
      - checkout
      # configure Docker to use gcloud as a credential helper
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: cd-demo-gke # rename
          tag: $CIRCLE_SHA1
      - gcp-gcr/push-image:
          image: cd-demo-gke # rename
          tag: $CIRCLE_SHA1
    
  deploy:
    description: Deploy image from GCR to GKE
    machine: true
    steps:
      # install gcloud and kubectl
      - gcp-gke/install
      # initialize the gcloud CLI
      - gcp-gke/update-kubeconfig-with-credentials:
          perform-login: true
          cluster: cd-demo-cluster # rename
      # update cluster with new Docker image
      - gcp-gke/rollout-image:
          deployment: cd-demo-cluster # rename
          cluster: cd-demo-cluster # rename
          container: dominic-backend 
          # edit the path and name of the image to match your container registry
          image: gcr.io/cd-demo-275213/cd-demo-gke # rename
          tag: $CIRCLE_SHA1

workflows:
  build_update_deploy:
    jobs:
      - build_and_test
      - build_push_image:
          requires:
            - build_and_test
      - deploy:
          requires:
            - build_push_image
