apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cd-demo-cluster
  labels:
    app: simple-backend
spec:
  selector:
    matchLabels:
      app: cd-demo-deploy
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cd-demo-deploy
        tier: backend
    spec:
      containers:
        - image: gcr.io/circleci-demo-2020-04-20/circleci-gke:v1
          name: website
          ports:
            - containerPort: 3000
              name: cd-demo-deploy

